"""Add core schema tables

Revision ID: 05cc847b4bc0
Revises: 16247e69e902
Create Date: 2026-07-24 07:37:31.376142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05cc847b4bc0'
down_revision: Union[str, Sequence[str], None] = '16247e69e902'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_prices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('commodity_name', sa.String(), nullable=False),
    sa.Column('average_market_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('highest_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('lowest_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('market_location', sa.String(), nullable=False),
    sa.Column('recorded_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contracts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('party_a_id', sa.String(length=36), nullable=False),
    sa.Column('party_b_id', sa.String(length=36), nullable=False),
    sa.Column('terms_description', sa.Text(), nullable=True),
    sa.Column('agreed_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('agreed_quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('contract_status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['party_a_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['party_b_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('buyer_id', sa.String(length=36), nullable=False),
    sa.Column('seller_id', sa.String(length=36), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_status', sa.String(), nullable=False),
    sa.Column('order_status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('seller_id', sa.String(length=36), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('price_per_unit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_type', sa.String(), nullable=False),
    sa.Column('quantity_available', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('harvest_date', sa.Date(), nullable=True),
    sa.Column('quality_certification_metadata', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deliveries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('transporter_name', sa.String(), nullable=True),
    sa.Column('current_location_lat', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('current_location_lng', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('delivery_status', sa.String(), nullable=False),
    sa.Column('estimated_time_of_arrival', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('location_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True))
    op.add_column('users', sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'longitude')
    op.drop_column('users', 'latitude')
    op.drop_column('users', 'location_name')
    op.drop_table('order_items')
    op.drop_table('deliveries')
    op.drop_table('products')
    op.drop_table('orders')
    op.drop_table('notifications')
    op.drop_table('contracts')
    op.drop_table('market_prices')
    # ### end Alembic commands ###
