"""add is_hidden to forum posts

Revision ID: 255f8e2c16b5
Revises: a1c4e9f2b6d3
Create Date: 2026-08-05 08:52:50.078569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '255f8e2c16b5'
down_revision: Union[str, Sequence[str], None] = 'a1c4e9f2b6d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'forum_posts',
        sa.Column('is_hidden', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('forum_posts', 'is_hidden', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forum_posts', 'is_hidden')
    # ### end Alembic commands ###
