"""add_images_chat_and_contract_items

Revision ID: 2e839e9819aa
Revises: 9db867ed1777
Create Date: 2026-07-27 05:06:20.774544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e839e9819aa'
down_revision: Union[str, Sequence[str], None] = '9db867ed1777'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sender_id', sa.String(length=36), nullable=False),
    sa.Column('receiver_id', sa.String(length=36), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('contract_id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=True),
    sa.Column('agreed_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('agreed_quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('contracts', 'agreed_quantity')
    op.drop_column('contracts', 'agreed_price')
    op.add_column('products', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('profile_image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_image_url')
    op.drop_column('products', 'image_url')
    op.add_column('contracts', sa.Column('agreed_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('contracts', sa.Column('agreed_quantity', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_table('contract_items')
    op.drop_table('chat_messages')
    # ### end Alembic commands ###
