"""add payment and delivery method to order

Revision ID: 3927b7170efb
Revises: d0bf68eb892c
Create Date: 2026-07-31 08:52:40.726805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3927b7170efb'
down_revision: Union[str, Sequence[str], None] = 'd0bf68eb892c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('orders', sa.Column('payment_method', sa.String(), nullable=False, server_default='KHQR'))
    op.add_column('orders', sa.Column('delivery_method', sa.String(), nullable=False, server_default='DELIVERY'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivery_method')
    op.drop_column('orders', 'payment_method')
    # ### end Alembic commands ###
