"""remove_category_id_from_contract_items

Revision ID: 9ef63ef0f896
Revises: 2e839e9819aa
Create Date: 2026-07-27 06:21:46.645728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ef63ef0f896'
down_revision: Union[str, Sequence[str], None] = '2e839e9819aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contract_items', 'product_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_constraint(op.f('contract_items_category_id_fkey'), 'contract_items', type_='foreignkey')
    op.drop_column('contract_items', 'category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract_items', sa.Column('category_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('contract_items_category_id_fkey'), 'contract_items', 'categories', ['category_id'], ['id'])
    op.alter_column('contract_items', 'product_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    # ### end Alembic commands ###
