"""add currency to order

Revision ID: a1c4e9f2b6d3
Revises: 3927b7170efb
Create Date: 2026-08-03 09:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1c4e9f2b6d3'
down_revision: Union[str, Sequence[str], None] = '3927b7170efb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('orders', sa.Column('currency', sa.String(), nullable=False, server_default='USD'))

    # Orders placed before this migration were never validated for a single
    # currency, so backfill each order's currency from its first line item's
    # product rather than leaving every historical order mislabeled as USD.
    op.execute(
        """
        UPDATE orders
        SET currency = COALESCE((
            SELECT p.currency
            FROM order_items oi
            JOIN products p ON p.id = oi.product_id
            WHERE oi.order_id = orders.id
            ORDER BY oi.id
            LIMIT 1
        ), 'USD')
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'currency')
    # ### end Alembic commands ###
