# Error Code Constants for API Response Mapping and Frontend (Flutter) Parsing

# --------- Auth Errors --------- #
EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"
PHONE_NUMBER_ALREADY_EXISTS = "PHONE_NUMBER_ALREADY_EXISTS"
INCORRECT_CREDENTIALS = "INCORRECT_CREDENTIALS"
ACCOUNT_LOCKED = "ACCOUNT_LOCKED"
INACTIVE_USER = "INACTIVE_USER"
USER_NOT_FOUND = "USER_NOT_FOUND"
COULD_NOT_VALIDATE_CREDENTIALS = "COULD_NOT_VALIDATE_CREDENTIALS"
INVALID_EMAIL_FORMAT = "INVALID_EMAIL_FORMAT"
PASSWORD_MIN_8_CHARACTERS = "PASSWORD_MIN_8_CHARACTERS"

# --------- Generic Errors --------- #
INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
DATABASE_ERROR = "DATABASE_ERROR"
VALIDATION_ERROR = "VALIDATION_ERROR"
NOT_AUTHENTICATED = "NOT_AUTHENTICATED"
NOT_AUTHORIZED = "NOT_AUTHORIZED"

# --------- Model Not Found Errors --------- #
CATEGORY_NOT_FOUND = "CATEGORY_NOT_FOUND"
PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND"
ORDER_NOT_FOUND = "ORDER_NOT_FOUND"
CONTRACT_NOT_FOUND = "CONTRACT_NOT_FOUND"
DELIVERY_NOT_FOUND = "DELIVERY_NOT_FOUND"
NOTIFICATION_NOT_FOUND = "NOTIFICATION_NOT_FOUND"
FORUM_POST_NOT_FOUND = "FORUM_POST_NOT_FOUND"
CONTENT_REPORT_NOT_FOUND = "CONTENT_REPORT_NOT_FOUND"
CANNOT_ORDER_OWN_PRODUCT = "CANNOT_ORDER_OWN_PRODUCT"
ORDER_CANNOT_BE_CANCELLED = "ORDER_CANNOT_BE_CANCELLED"
CHAT_SENDER_CANNOT_BE_RECEIVER = "CHAT_SENDER_CANNOT_BE_RECEIVER"
CANNOT_MODIFY_ITEMS_AFTER_DRAFT = "CANNOT_MODIFY_ITEMS_AFTER_DRAFT"
CONTRACT_PRODUCT_OWNER_MISMATCH = "CONTRACT_PRODUCT_OWNER_MISMATCH"
START_DATE_MUST_BE_IN_FUTURE = "START_DATE_MUST_BE_IN_FUTURE"
END_DATE_MUST_BE_AFTER_START_DATE = "END_DATE_MUST_BE_AFTER_START_DATE"

ADDRESS_CHANGE_REQUEST_ALREADY_RESOLVED = "ADDRESS_CHANGE_REQUEST_ALREADY_RESOLVED"
ADDRESS_CHANGE_REQUEST_ALREADY_PENDING = "ADDRESS_CHANGE_REQUEST_ALREADY_PENDING"
ADDRESS_CHANGE_REQUEST_NOT_FOUND = "ADDRESS_CHANGE_REQUEST_NOT_FOUND"

PRODUCT_HAS_RELATED_INFO = "PRODUCT_HAS_RELATED_INFO"

COOPERATIVE_MEMBER_NOT_FOUND = "COOPERATIVE_MEMBER_NOT_FOUND"
COOPERATIVE_MEMBER_ALREADY_EXISTS = "COOPERATIVE_MEMBER_ALREADY_EXISTS"
CANNOT_INVITE_SELF = "CANNOT_INVITE_SELF"

ORDER_ALREADY_PAID = "ORDER_ALREADY_PAID"
MULTIPLE_CURRENCIES_IN_ORDER = "MULTIPLE_CURRENCIES_IN_ORDER"
MULTIPLE_SELLERS_IN_ORDER = "MULTIPLE_SELLERS_IN_ORDER"
NO_ITEMS_IN_ORDER = "NO_ITEMS_IN_ORDER"
INSUFFICIENT_STOCK = "INSUFFICIENT_STOCK"
DELIVERY_LOCATION_REQUIRED = "DELIVERY_LOCATION_REQUIRED"
INVALID_ORDER_STATUS_TRANSITION = "INVALID_ORDER_STATUS_TRANSITION"
PAYMENT_NOT_CONFIRMED = "PAYMENT_NOT_CONFIRMED"

INVALID_OR_EXPIRED_CODE = "INVALID_OR_EXPIRED_CODE"
NO_EMAIL_ON_ACCOUNT = "NO_EMAIL_ON_ACCOUNT"

ONLY_SELLER_CAN_ACTIVATE_CONTRACT = "ONLY_SELLER_CAN_ACTIVATE_CONTRACT"
CONTRACT_ALREADY_RESOLVED = "CONTRACT_ALREADY_RESOLVED"

ORDER_NOT_DELIVERED = "ORDER_NOT_DELIVERED"
ORDER_ALREADY_REVIEWED = "ORDER_ALREADY_REVIEWED"

DISPUTE_NOT_FOUND = "DISPUTE_NOT_FOUND"
DISPUTE_ALREADY_OPEN = "DISPUTE_ALREADY_OPEN"
DISPUTE_ALREADY_RESOLVED = "DISPUTE_ALREADY_RESOLVED"
INVALID_DISPUTE_STATUS = "INVALID_DISPUTE_STATUS"