# Error Code Constants for API Response Mapping and Frontend (Flutter) Parsing

# --------- Auth Errors --------- #
EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"
PHONE_NUMBER_ALREADY_EXISTS = "PHONE_NUMBER_ALREADY_EXISTS"
INCORRECT_CREDENTIALS = "INCORRECT_CREDENTIALS"
INACTIVE_USER = "INACTIVE_USER"
USER_NOT_FOUND = "USER_NOT_FOUND"
COULD_NOT_VALIDATE_CREDENTIALS = "COULD_NOT_VALIDATE_CREDENTIALS"
INVALID_EMAIL_FORMAT = "INVALID_EMAIL_FORMAT"
PASSWORD_MIN_8_CHARACTERS = "PASSWORD_MIN_8_CHARACTERS"

# --------- Generic Errors --------- #
INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
VALIDATION_ERROR = "VALIDATION_ERROR"
NOT_AUTHENTICATED = "NOT_AUTHENTICATED"
NOT_AUTHORIZED = "NOT_AUTHORIZED"
PASSWORD_MIN_8_CHARACTERS = "PASSWORD_MIN_8_CHARACTERS"

# --------- Model Not Found Errors --------- #
CATEGORY_NOT_FOUND = "CATEGORY_NOT_FOUND"
PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND"
ORDER_NOT_FOUND = "ORDER_NOT_FOUND"
CONTRACT_NOT_FOUND = "CONTRACT_NOT_FOUND"
DELIVERY_NOT_FOUND = "DELIVERY_NOT_FOUND"
NOTIFICATION_NOT_FOUND = "NOTIFICATION_NOT_FOUND"
CANNOT_ORDER_OWN_PRODUCT = "CANNOT_ORDER_OWN_PRODUCT"
ORDER_CANNOT_BE_CANCELLED = "ORDER_CANNOT_BE_CANCELLED"
CHAT_SENDER_CANNOT_BE_RECEIVER = "CHAT_SENDER_CANNOT_BE_RECEIVER"
CANNOT_MODIFY_ITEMS_AFTER_DRAFT = "CANNOT_MODIFY_ITEMS_AFTER_DRAFT"
CONTRACT_PRODUCT_OWNER_MISMATCH = "CONTRACT_PRODUCT_OWNER_MISMATCH"
START_DATE_MUST_BE_IN_FUTURE = "START_DATE_MUST_BE_IN_FUTURE"
END_DATE_MUST_BE_AFTER_START_DATE = "END_DATE_MUST_BE_AFTER_START_DATE"
